name: vllm-pgvector
distribution_spec:
  description: vllm with pgvector
  providers:
    inference: remote::vllm
    inference: inline::sentence-transformers
    vector_io: remote::pgvector
    safety: inline::llama-guard
    agents: inline::meta-reference
    telemetry: inline::meta-reference
    agents: inline::meta-reference
    eval: inline::meta-reference
    datasetio: remote::huggingface
    datasetio: inline::localfs
    scoring: inline::basic
    scoring: inline::llm-as-judge
    scoring: inline::braintrust
    telemetry: inline::meta-reference
    tool_runtime: remote::brave-search
    tool_runtime: remote::tavily-search
    tool_runtime: inline::code-interpreter
    tool_runtime: inline::rag-runtime
    tool_runtime: remote::model-context-protocol
image_type: container
